version: '3'

services:
  db:
    image: mysql:5.7
    restart: on-failure
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'vexim'
      MYSQL_USER: 'vexim'
      MYSQL_PASSWORD: 'CHANGE'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./setup/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql:ro,cached

  php:
    build: docker/php
    restart: on-failure
    user: '${UID:-1000}'
    volumes:
      - mail_dir:/var/vmail:rw
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro,cached
      - ./docker/php/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini:ro,cached
      - ./vexim:/srv/app:ro,cached
      - ./vexim/config/variables.php.example:/srv/app/config/variables.php:ro,cached
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=vexim}'
    depends_on:
      - db
    links:
      - db

  nginx:
    image: nginx:1-alpine-slim
    restart: on-failure
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ./vexim:/srv/app:ro,cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
    depends_on:
      - php
    links:
      - php

volumes:
  db_data:
  mail_dir:
